# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RaamennResipi' do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
end

