# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RaamennResipi' do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'React', path: '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end
